# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute a 'FarmHash' digest for a vector of strings
#'
#' @param sv Vector of strings for which a hash digest is requested
#' @return A vector of \code{integer64} values (using the \pkg{bit64}
#' package to \sQuote{decode} the appropriate binary payload from a numeric
#' vector).
#' @examples
#' if (requireNamespace("bit64", quietly=TRUE)) {
#'    suppressMessages(library(bit64))
#' }
#' farmhash(c("foo", "bar", "baz"))
farmhash <- function(sv) {
    .Call(`_RcppFarmHash_farmhash`, sv)
}

